/** @type {import("jest").Config} */
module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: [
    "<rootDir>/tests/runtime_execution",
    "<rootDir>/tests/orchestration",
    "<rootDir>/tests/workflow",
    "<rootDir>/tests/contracts",
    "<rootDir>/tests/construction_selection",
    "<rootDir>/tests/construction_selection_result",
    "<rootDir>/tests/construction_plan",
    "<rootDir>/tests/construction_planning_contract",
    "<rootDir>/tests/construction_planning_definition",
    "<rootDir>/tests/construction_planning_specification",
    "<rootDir>/tests/construction_planning_manifest",
    "<rootDir>/tests/construction_planning_consumption_boundary",
    "<rootDir>/tests/construction_structural_responsibility_boundary",
    "<rootDir>/tests/construction_responsibility_structural_interface_definition",
    "<rootDir>/tests/construction_responsibility_structural_compatibility_validation",
    "<rootDir>/tests/construction_responsibility_structural_normalization",
    "<rootDir>/tests/extension_governance",
    "<rootDir>/tests/extension_development_framework",
    "<rootDir>/tests/extensions/asa_ops",
    "<rootDir>/tests/extensions/asa_connect",
    "<rootDir>/tests/extensions/asa_ai",
    "<rootDir>/tests/extensions/asa_validation",
    "<rootDir>/tests/extensions/asa_coordination",
    "<rootDir>/tests/extensions/asa_scenario",
    "<rootDir>/tests/architecture_evolution",
    "<rootDir>/tests/architecture_validation",
    "<rootDir>/tests/architecture_operations",
    "<rootDir>/tests/architecture_extension",
    "<rootDir>/tests/architecture_evolution_layer",
    "<rootDir>/tests/architecture_intelligence",
    "<rootDir>/tests/architecture_traceability",
  ],
  testMatch: ["**/*.test.ts", "**/*.spec.ts"],
  moduleFileExtensions: ["ts", "js", "json"],
  clearMocks: true,
};
