# -*- coding: utf-8 -*-
"""SOX PROTOCOL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_sf9ERBGN8jLGGHwZa8lgw5NPxYqwV1
"""

# ================================
# Discord通知モジュール（毅さん専用）
# ================================
import requests

DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1524413853293871106/sQWYe04jZnQXB5b2UsEvbrt2SbWiKwAB79zeuOO7ZZX5_6xV0ZbX5XAX0tcW_crdRyH3"

def send_discord(message: str):
    payload = {
        "content": message
    }
    try:
        requests.post(DISCORD_WEBHOOK_URL, json=payload)
    except Exception as e:
        print("Discord送信エラー:", e)

# ================================
#  SOX PROTOCOL（毅さん仕様）
#  季節期待値 → ANOMALY_FACTOR 自動生成版
# ================================

import datetime
import yfinance as yf
import pandas as pd
import json
import os

LOG_FILE = "sox_batting_log.json"

# ================================
#  季節期待値 → ANOMALY_FACTOR 自動生成
# ================================
def generate_anomaly_factor():
    today = datetime.date.today()
    start = today - datetime.timedelta(days=365 * 20)

    df = yf.download("SOXX", start=start.strftime("%Y-%m-%d"), end=today.strftime("%Y-%m-%d"))
    df = df[["Close"]].dropna()

    df["date"] = df.index
    df["mmdd"] = df["date"].dt.strftime("%m-%d")
    df["year"] = df["date"].dt.year

    CYCLE_WINDOWS = {
        1: {"buy": ("02-10", "02-28"), "sell": ("04-01", "04-20")},
        2: {"buy": ("05-01", "05-31"), "sell": ("07-20", "07-31")},
        3: {"buy": ("08-25", "09-07"), "sell": ("09-10", "09-20")},
        4: {"buy": ("10-10", "10-20"), "sell": ("12-10", "12-20")},
    }

    anomaly_factor = {}

    for cycle_id, win in CYCLE_WINDOWS.items():
        buy_start, buy_end = win["buy"]
        sell_start, sell_end = win["sell"]

        buy_drops = []
        sell_rises = []

        for year in df["year"].unique():

            buy_df = df[(df["year"] == year) & (df["mmdd"] >= buy_start) & (df["mmdd"] <= buy_end)]
            if len(buy_df) > 1:
                start_price = buy_df.iloc[0]["Close"]
                start_price = float(start_price.iloc[0] if hasattr(start_price, "iloc") else start_price)

                end_price = buy_df.iloc[-1]["Close"]
                end_price = float(end_price.iloc[0] if hasattr(end_price, "iloc") else end_price)

                buy_drops.append((end_price - start_price) / start_price)

            sell_df = df[(df["year"] == year) & (df["mmdd"] >= sell_start) & (df["mmdd"] <= sell_end)]
            if len(sell_df) > 1:
                start_price = sell_df.iloc[0]["Close"]
                start_price = float(start_price.iloc[0] if hasattr(start_price, "iloc") else start_price)

                end_price = sell_df.iloc[-1]["Close"]
                end_price = float(end_price.iloc[0] if hasattr(end_price, "iloc") else end_price)

                sell_rises.append((end_price - start_price) / start_price)

        buy_exp  = sum(buy_drops) / len(buy_drops) if buy_drops else 0
        sell_exp = sum(sell_rises) / len(sell_rises) if sell_rises else 0

        # あなた仕様の補正係数（強度をあなたの手計算版に合わせる）
        factor = 1 - buy_exp * 10

        # 暴走防止
        factor = max(0.50, min(1.50, factor))

        anomaly_factor[cycle_id] = round(factor, 2)

    return anomaly_factor

# 自動生成（ここが重要）
ANOMALY_FACTOR = generate_anomaly_factor()
print("季節補正係数（自動生成）:", ANOMALY_FACTOR)

# ================================
#  打席ログ
# ================================
def load_log():
    if not os.path.exists(LOG_FILE):
        return {"batting": [], "year": datetime.date.today().year}
    with open(LOG_FILE, "r") as f:
        return json.load(f)

def save_log(log):
    with open(LOG_FILE, "w") as f:
        json.dump(log, f, indent=4)

def safe_float(x):
    if hasattr(x, "item"):
        return float(x.item())
    return float(x)

# ================================
# RSI計算
# ================================
def calc_RSI(series, period=14):
    delta = series.diff()
    up = delta.clip(lower=0)
    down = -1 * delta.clip(upper=0)
    ma_up = up.rolling(period).mean()
    ma_down = down.rolling(period).mean()
    RS = ma_up / ma_down
    return 100 - (100 / (1 + RS))

# ================================
# 4大サイクル
# ================================
CYCLE_WINDOWS = {
    1: {"name": "冬春（納税・還付金）", "buy": ("02-10", "02-28"), "sell": ("04-01", "04-20")},
    2: {"name": "Sell in May", "buy": ("05-01", "05-31"), "sell": ("07-20", "07-31")},
    3: {"name": "夏秋（ジャクソンホール）", "buy": ("08-25", "09-07"), "sell": ("09-10", "09-20")},
    4: {"name": "秋冬（決算・年末ラリー）", "buy": ("10-10", "10-20"), "sell": ("12-10", "12-20")},
}

TARGET_REBOUND = 0.10

# ================================
# サイクル自動判定
# ================================
def detect_cycle(today_mmdd):
    for cycle_id, win in CYCLE_WINDOWS.items():
        buy_start, buy_end = win["buy"]
        sell_start, sell_end = win["sell"]

        if buy_start <= today_mmdd <= buy_end:
            return cycle_id, win["name"], "買場帯"

        if sell_start <= today_mmdd <= sell_end:
            return cycle_id, win["name"], "売場帯"

    return None, "サイクル外", "サイクル外"

# ================================
# メインロジック
# ================================
def execute_sox_protocol(SOX_TODAY, SOX_MOTOMOTO, SOX_HYOKA):

    today = datetime.date.today()
    today_mmdd = today.strftime("%m-%d")

    CURRENT_CYCLE, cycle_name, cycle_phase = detect_cycle(today_mmdd)

    log = load_log()
    if log["year"] != today.year:
        log = {"batting": [], "year": today.year}
    batting_count = len(log["batting"])

    anomaly_factor = ANOMALY_FACTOR.get(CURRENT_CYCLE, 1.0)

    sox = yf.download("^SOX", period="180d", interval="1d", auto_adjust=False)["Close"]
    vix = yf.download("^VIX", period="30d", interval="1d", auto_adjust=False)["Close"]
    sox_f = yf.download("SOX=F", period="5d", interval="1h", auto_adjust=False)["Close"]
    nasdaq = yf.download("^IXIC", period="5d", interval="1d", auto_adjust=False)["Close"]
    nasdaq_f = yf.download("NQ=F", period="5d", interval="1h", auto_adjust=False)["Close"]
    jpy = yf.download("JPY=X", period="5d", interval="1h", auto_adjust=False)["Close"]

    SOX_INDEX = safe_float(sox.iloc[-1])
    MA5 = safe_float(sox.rolling(5).mean().iloc[-1])
    MA25 = safe_float(sox.rolling(25).mean().iloc[-1])
    RSI_14 = safe_float(calc_RSI(sox).iloc[-1])

    weekly = sox.iloc[::5]
    WMA5 = safe_float(weekly.rolling(5).mean().iloc[-1])
    WMA25 = safe_float(weekly.rolling(25).mean().iloc[-1])
    weekly_gc = (WMA5 > WMA25)

    SOX_F = safe_float(sox_f.iloc[-1])
    NASDAQ_SPOT = safe_float(nasdaq.iloc[-1])
    NASDAQ_F = safe_float(nasdaq_f.iloc[-1])
    JPY = safe_float(jpy.iloc[-1])
    JPY_prev = safe_float(jpy.iloc[-2])
    VIX = safe_float(vix.iloc[-1])

    sox_f_move = (SOX_F - SOX_INDEX) / SOX_INDEX * 100
    nasdaq_f_move = (NASDAQ_F - NASDAQ_SPOT) / NASDAQ_SPOT * 100
    jpy_move = (JPY - JPY_prev) / JPY_prev * 100

    pm_overheat = (
        sox_f_move >= 1.5 or
        nasdaq_f_move >= 1.0
    )

    crash_zone = VIX > 20

    KOSU = SOX_HYOKA / SOX_MOTOMOTO
    SOX_OVERPRICE_LINE = SOX_MOTOMOTO * 1.15
    REAL_OVERPRICE_LINE = SOX_OVERPRICE_LINE * KOSU
    is_overpriced = SOX_HYOKA > REAL_OVERPRICE_LINE

    SOX_MOVE_RATE = (SOX_HYOKA - SOX_MOTOMOTO) / SOX_MOTOMOTO

    BOTTOM_THRESHOLD = -0.06 * anomaly_factor
    is_my_bottom = SOX_MOVE_RATE <= BOTTOM_THRESHOLD

    is_market_bottom = (
        RSI_14 <= 45 and
        SOX_INDEX <= MA25 * 0.97 and
        MA5 < MA25 and
        weekly_gc
    )

    rebound_expect = ((MA25 - SOX_INDEX) / SOX_INDEX) * anomaly_factor * 100

    print("=" * 72)
    print(f"📅 判定日: {today}")
    print(f"🎯 年間打席数: {batting_count}/4")
    print(f"🔄 現在のサイクル: {cycle_name}")
    print(f"📍 サイクル帯: {cycle_phase}")
    print(f"📘 補正係数: {anomaly_factor}")
    print("-" * 72)

    print("📊【AM判定】")
    print(f" SOX指数: {SOX_INDEX:,.2f}")
    print(f" RSI(14): {RSI_14:.2f}")
    print(f" MA5: {MA5:,.2f}")
    print(f" MA25: {MA25:,.2f}")
    print(f" 週足GC: {weekly_gc}")
    print(f" 市場底の手前: {is_market_bottom}")
    print("-" * 72)

    print("📊【PM判定】")
    print(f" SOX先物変化率: {sox_f_move:.2f}%")
    print(f" NASDAQ先物変化率: {nasdaq_f_move:.2f}%")
    print(f" ドル円変化率（参考値）: {jpy_move:.2f}%")
    print(f" PM過熱判定: {pm_overheat}")
    print("-" * 72)

    print("💹【あなたのSOXポジション】")
    print(f" 取得単価: {SOX_MOTOMOTO:,}円")
    print(f" 現在評価額: {SOX_HYOKA:,}円")
    print(f" 口数: {KOSU:.4f}口")
    print(f" 上下運動率: {SOX_MOVE_RATE*100:.2f}%")
    print(f" 割高判定: {is_overpriced}")
    print(f" 反発期待値（補正後）: {rebound_expect:.2f}%")
    print("-" * 72)

    if crash_zone and is_my_bottom and not is_overpriced:
        return "🟣【暴落ゾーン買い】反発期待値高い。"

    if (
        is_my_bottom and
        is_market_bottom and
        not pm_overheat and
        not is_overpriced and
        batting_count < 4
    ):
        log["batting"].append(str(today))
        save_log(log)
        return "🔥【買いGO強化】反発10％ゾーン。（打席記録済み）"

    if MA5 < MA25:
        return "⚠️【買い弱化】日足DC。静観。"

    if is_overpriced:
        return "⚠️【買い見送り】割高ライン超え。静観。"

    return "➔【静観】まだ買いラインに未達。"

SOX_TODAY    = int(input("① 今日のSOX基準価額: "))
SOX_MOTOMOTO = int(input("② あなたのSOX取得単価: "))
SOX_HYOKA    = int(input("③ あなたのSOX現在評価額: "))

result = execute_sox_protocol(SOX_TODAY, SOX_MOTOMOTO, SOX_HYOKA)
print(result)
print("=" * 72)

send_discord(result)