name: SOX PROTOCOL

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日0時に実行
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Python をセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 必要なライブラリをインストール
        run: |
          pip install yfinance
          pip install pandas
          pip install numpy
          pip install discord.py

      - name: SOX PROTOCOL を実行
        run: python sox_protocol.py
